network:
  port: 8080
  proxy-protocol: socks5
  proxy-host: 127.0.0.1
  proxy-port: 7890
external-service:
  google-custom-search:
    api-key: ENC(4NENKkiWYYSEU5dRO+O/jBjgoCTkcjgBZtZ1ce5V/pAd7V7zRjzXVnavoIQvNko+)
    engine-id:
      entire: f18c2db8bf8be424d
      wikipedia: 9614938ae8c634af8
      music-platform: 30be9fbaf45414c67
  perplexity-ai:
    api-key: ENC(v1Ke6Qs1a6bt+Ys+nzwftQHm/B3vA9fSzcVARGQVXdT2fYakY/WdnVy+X5i4A1Y8E/y/Pa6ebOrLb+8m0CWD/Q==)
text-checker:
  character-blacklist:
    common:
      - ' ' # Most of the case, it should be ' '
    japanese:
      - '·' # Most of the case, it should be '・'
      - '~' # Most of the case, it should be '〜'
    latin:
    zh-hans:
  # The ends of the ranges are inclusive.
  range-blacklist:
    common:
      - start: 0xFF01
        end: 0xFF5A
    cyrillic:
      - start: 0x0E3F
    latin:
      - start: 0x0250