network:
  port: 8080
  proxy-protocol: http
  proxy-host: 127.0.0.1
  proxy-port: 7890
external-service:
  google-custom-search:
    api-key: ENC(hJY4xOYpq8Bf17UUvVOqBDmPwtOclWPK)
    engine-id:
      entire: f18c2db8bf8be424d
      wikipedia: 9614938ae8c634af8
      music-platform: 30be9fbaf45414c67
  perplexity-ai:
    api-key: ENC(hJY4xOYpq8Bf17UUvVOqBDmPwtOclWPK)
text-checker:
  character-blacklist:
    common:
      - ' ' # Most of the case, it should be ' '
    japanese:
      - '·' # Most of the case, it should be '・'
      - '~' # Most of the case, it should be '〜'
    latin:
    zh-hans:
  # The ends of the ranges are inclusive.
  range-blacklist:
    common:
      - start: 0xFF01
        end: 0xFF5A
    cyrillic:
      - start: 0x0E3F
    latin:
      - start: 0x0250